# docker-compose.prod.yml
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multivendor-app-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      PORT: 3000
      NODE_ENV: production
    restart: unless-stopped